import fresh_tomatoes
import media

#Create instances for each Harry Potter Movie in the series.
#Each movie includes Title, Story, Poster Image, and Trailer.
hp1 = media.Movie("Harry Potter and the Sorcerer's Stone", "Adaptation of the first of J.K. Rowling's popular children's novels about Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents' mysterious deaths.", "http://www.gstatic.com/tv/thumb/movieposters/28630/p28630_p_v8_at.jpg", "https://www.youtube.com/watch?v=PbdM1db3JbY")

hp2 = media.Movie("Harry Potter and the Chamber of Secrets", "The follow-up to 'Harry Potter and the Sorcerer's Stone' finds young wizard Harry Potter (Daniel Radcliffe) and his friends, Ron (Rupert Grint) and Hermione (Emma Watson), facing new challenges during their second year at Hogwarts School of Witchcraft and Wizardry as they try to discover a dark force that is terrorizing the school.", "http://t0.gstatic.com/images?q=tbn:ANd9GcTltzcooPkGcy1fKKqzSuO8U6S9XBpNDR9MuYc9SS_L5AbAn66O", "https://www.youtube.com/watch?v=uU-ET1FAv3Y")

hp3 = media.Movie("Harry Potter and the Prisoner of Azkaban", "Harry Potter's (Daniel Radcliffe) third year at Hogwarts starts off badly when he learns deranged killer Sirius Black (Gary Oldman) has escaped from Azkaban prison and is bent on murdering the teenage wizard. While Hermione's (Emma Watson) cat torments Ron's (Rupert Grint) sickly rat, causing a rift among the trio, a swarm of nasty Dementors is sent to protect the school from Black. A mysterious new teacher helps Harry learn to defend himself, but what is his secret tie to Sirius Black?", "http://www.gstatic.com/tv/thumb/movieposters/34483/p34483_p_v8_ap.jpg", "https://www.youtube.com/watch?v=lAxgztbYDbs")

hp4 = media.Movie("Harry Potter and the Goblet of Fire", "The fourth movie in the Harry Potter franchise sees Harry (Daniel Radcliffe) returning for his fourth year at Hogwarts School of Witchcraft and Wizardry, along with his friends, Ron (Rupert Grint) and Hermione (Emma Watson). There is an upcoming tournament between the three major schools of magic, with one participant selected from each school by the Goblet of Fire. When Harry's name is drawn, even though he is not eligible and is a fourth player, he must compete in the dangerous contest.", "http://www.gstatic.com/tv/thumb/movieposters/90599/p90599_p_v8_aq.jpg", "https://www.youtube.com/watch?v=PFWAOnvMd1Q")

hp5 = media.Movie("Harry Potter and the Order of the Pheonix", "Now in his fifth year at Hogwarts, Harry (Daniel Radcliffe) learns that many in the wizarding community do not know the truth of his encounter with Lord Voldemort. Cornelius Fudge, minister of Magic, appoints his toady, Dolores Umbridge, as Defense Against the Dark Arts teacher, for he fears that professor Dumbledore will take his job. But her teaching is deficient and her methods, cruel, so Harry prepares a group of students to defend the school against a rising tide of evil.", "http://www.gstatic.com/tv/thumb/movieposters/166014/p166014_p_v8_al.jpg", "https://www.youtube.com/watch?v=WIj9DYJ5EKk")

hp6 = media.Movie("Harry Potter and the Half-Blood Prince", "As Death Eaters wreak havoc in both Muggle and Wizard worlds, Hogwarts is no longer a safe haven for students. Though Harry (Daniel Radcliffe) suspects there are new dangers lurking within the castle walls, Dumbledore is more intent than ever on preparing the young wizard for the final battle with Voldemort. Meanwhile, teenage hormones run rampant through Hogwarts, presenting a different sort of danger. Love may be in the air, but tragedy looms, and Hogwarts may never be the same again.", "http://www.gstatic.com/tv/thumb/movieposters/176377/p176377_p_v8_ak.jpg", "https://www.youtube.com/watch?v=JYLdTuL9Wjw")

hp7_1 = media.Movie("Harry Potter and the Deathly Hollows: Part 1", "Without the guidance and protection of their professors, Harry (Daniel Radcliffe), Ron (Rupert Grint) and Hermione (Emma Watson) begin a mission to destroy the Horcruxes, the sources of Voldemort's immortality. Though they must rely on one another more than ever, dark forces threaten to tear them apart. Voldemort's Death Eaters have seized control of the Ministry of Magic and Hogwarts, and they are searching for Harry -- even as he and his friends prepare for the ultimate showdown.", "http://t3.gstatic.com/images?q=tbn:ANd9GcTobkzVSJU5oZ9Pv_6bM0_o4RF_zFA9jyNwdHATG90vKxyhOk5x", "https://www.youtube.com/watch?v=YzfEH0UPEBo")

hp7_2 = media.Movie("Harry Potter and the Deathly Hollows: Part 2", "A clash between good and evil awaits as young Harry (Daniel Radcliffe), Ron (Rupert Grint) and Hermione (Emma Watson) prepare for a final battle against Lord Voldemort (Ralph Fiennes). Harry has grown into a steely lad on a mission to rid the world of evil. The friends must search for the Horcruxes that keep the dastardly wizard immortal. Harry and Voldemort meet at Hogwarts Castle for an epic showdown where the forces of darkness may finally meet their match.", "http://t3.gstatic.com/images?q=tbn:ANd9GcTgXSuLAFerQGZdPCWv8EHI_ucQq6RTl3xf91F4aN54PDA_oCtB", "https://www.youtube.com/watch?v=mObK5XD8udk")

#Create list of all instances in the series.
movies = [hp1, hp2, hp3, hp4, hp5, hp6, hp7_1, hp7_2]
